"""empty message

Revision ID: 0082de551cd3
Revises: e8e1c080480b
Create Date: 2023-05-04 20:25:32.542632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0082de551cd3'
down_revision = 'e8e1c080480b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('files')

    # ### end Alembic commands ###
