"""empty message

Revision ID: 147ea94a3335
Revises: 3db9590bf173
Create Date: 2023-04-22 04:38:54.806089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147ea94a3335'
down_revision = '3db9590bf173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
