"""empty message

Revision ID: 261626235895
Revises: 6ccaf63ec007
Create Date: 2023-04-24 13:39:49.819377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261626235895'
down_revision = '6ccaf63ec007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('tallernom',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=110),
               existing_nullable=True)
        batch_op.alter_column('regiontall',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=110),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('regiontall',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('tallernom',
               existing_type=sa.String(length=110),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
