"""empty message

Revision ID: 5063a86a7dca
Revises: 
Create Date: 2023-04-19 20:56:34.949063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5063a86a7dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('articulonom', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('promocion', sa.Boolean(), nullable=False),
    sa.Column('precio_oferta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talleres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('taller_articulo',
    sa.Column('talleres_id', sa.Integer(), nullable=False),
    sa.Column('articulos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articulos_id'], ['articulos.id'], ),
    sa.ForeignKeyConstraint(['talleres_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('talleres_id', 'articulos_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('roles_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id', 'roles_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('comunicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.Column('destino', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tipos_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipos_id'], ['tipos.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'tipos_id', 'users_id'),
    sa.UniqueConstraint('autor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunicacion')
    op.drop_table('users')
    op.drop_table('taller_articulo')
    op.drop_table('tipos')
    op.drop_table('talleres')
    op.drop_table('roles')
    op.drop_table('articulos')
    # ### end Alembic commands ###
