"""empty message

Revision ID: 6259a5fed776
Revises: 749b897a0265
Create Date: 2023-04-20 19:42:21.216200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6259a5fed776'
down_revision = '749b897a0265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipopago', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('pagos_tipospago_key', type_='unique')
        batch_op.create_unique_constraint(None, ['tipopago'])
        batch_op.drop_column('tipospago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipospago', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('pagos_tipospago_key', ['tipospago'])
        batch_op.drop_column('tipopago')

    # ### end Alembic commands ###
