"""empty message

Revision ID: 62ba686063f2
Revises: 261626235895
Create Date: 2023-04-25 03:32:48.899559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ba686063f2'
down_revision = '261626235895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud', sa.Float(precision=20), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(precision=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')

    # ### end Alembic commands ###
