"""empty message

Revision ID: 6da34cc96157
Revises: 74b39aa8d8e4
Create Date: 2023-04-22 14:04:18.416426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da34cc96157'
down_revision = '74b39aa8d8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('articulonom',
               existing_type=sa.VARCHAR(length=190),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('articulonom',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=190),
               existing_nullable=False)

    # ### end Alembic commands ###
