"""empty message

Revision ID: 749b897a0265
Revises: ffd55d183813
Create Date: 2023-04-20 16:44:47.358644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749b897a0265'
down_revision = 'ffd55d183813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tipospago', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipospago')
    )
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regiontall', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('direcciontall', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('pagos_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pagos', ['pagos_id'], ['id'])
        batch_op.drop_column('region')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pagos_id')
        batch_op.drop_column('direcciontall')
        batch_op.drop_column('regiontall')

    op.drop_table('pagos')
    # ### end Alembic commands ###
