"""empty message

Revision ID: 74b39aa8d8e4
Revises: cd07eaa502fb
Create Date: 2023-04-22 05:56:51.419030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74b39aa8d8e4'
down_revision = 'cd07eaa502fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('articulonom',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=190),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.alter_column('articulonom',
               existing_type=sa.String(length=190),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
