"""empty message

Revision ID: 7b9024dc39d0
Revises: f900eaefd5ec
Create Date: 2023-05-04 19:10:39.901839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9024dc39d0'
down_revision = 'f900eaefd5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.alter_column('tipos_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.alter_column('tipos_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
