"""empty message

Revision ID: a03091a93a5d
Revises: d7da08275f4c
Create Date: 2023-04-27 12:47:52.521922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03091a93a5d'
down_revision = 'd7da08275f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))
        batch_op.drop_constraint('comunicacion_users_id_fkey', type_='foreignkey')
        batch_op.drop_column('users_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comunicacion_users_id_fkey', 'users', ['users_id'], ['id'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###
