"""empty message

Revision ID: bbb2bb632aba
Revises: 
Create Date: 2023-05-07 01:22:25.339563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbb2bb632aba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['roles_id'], ['id'])
        batch_op.drop_column('files')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('files', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data')
        batch_op.drop_column('roles_id')

    # ### end Alembic commands ###
