"""empty message

Revision ID: bdbe9d35bedc
Revises: a2b7f63e15a2
Create Date: 2023-04-24 05:28:34.857134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbe9d35bedc'
down_revision = 'a2b7f63e15a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('tallernom',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=130),
               existing_nullable=True)
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tallernom',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
