"""empty message

Revision ID: cd07eaa502fb
Revises: 147ea94a3335
Create Date: 2023-04-22 04:53:20.097499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd07eaa502fb'
down_revision = '147ea94a3335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
