"""empty message

Revision ID: d7da08275f4c
Revises: f0c7f3571476
Create Date: 2023-04-26 02:53:44.764738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7da08275f4c'
down_revision = 'f0c7f3571476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mantencion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('indumentaria', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bicicletas', sa.Integer(), nullable=True))
        batch_op.drop_column('promocion')
        batch_op.drop_column('precio_oferta')
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articulos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio_oferta', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('promocion', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('bicicletas')
        batch_op.drop_column('indumentaria')
        batch_op.drop_column('mantencion')

    # ### end Alembic commands ###
