"""empty message

Revision ID: dfbf56e2820c
Revises: 6259a5fed776
Create Date: 2023-04-20 19:46:33.833383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbf56e2820c'
down_revision = '6259a5fed776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('tipopago',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('tipos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('tipopago',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
