"""empty message

Revision ID: e8e1c080480b
Revises: f900eaefd5ec
Create Date: 2023-05-04 19:11:42.323351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e1c080480b'
down_revision = 'f900eaefd5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.drop_column('destino')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(length=220), autoincrement=False, nullable=False))

    with op.batch_alter_table('comunicacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
