"""empty message

Revision ID: f0c7f3571476
Revises: 62ba686063f2
Create Date: 2023-04-25 17:36:47.135528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c7f3571476'
down_revision = '62ba686063f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_column('latitud')
        batch_op.drop_column('longitud')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitud', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.REAL(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
