"""empty message

Revision ID: ffd55d183813
Revises: 36243120a74f
Create Date: 2023-04-20 03:35:39.303443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd55d183813'
down_revision = '36243120a74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('roles_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('users_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
